export const ROUTES = {
  ROOT: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  SSO_CALLBACK: "/sso-callback",
  ACCOUNT: "/account",
  ACCOUNT_BANKS: "/account/banks",
  EDIT_PROFILE: "/edit-profile",
  EDIT_ADDRESSES: "/edit-addresses",
  SEND: "/send",
  SEND_SELF: "/send/self",
  RECIPIENTS: "/recipients",
  RECIPIENTS_NEW: "/recipients/new",
  ACTIVITY: "/activity",
  BALANCE: "/balance",
  NOTIFICATIONS: "/notifications",
  REFERRAL: "/referral",
  SUPPORT: "/support",
  KYC: "/kyc",
  LINK_BANK: "/link-bank",
  MAINTENANCE: "/maintenance",
  ONBOARDING: {
    PROFILE: "/onboarding/profile",
    REFERRAL: "/onboarding/referral",
    ADDRESS: "/onboarding/address",
    WAITLIST: "/onboarding/waitlist",
    BLOCKED: "/onboarding/blocked",
  },
} as const;
